### ISSUE TITLE
Allow configurable HTTP/HTTPS for WF queries and, in HTTPS requests, make verify=False configurable

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#183]
We want `Node`s to fail tests if their certs aren't valid, but WebFinger, for example, requires valid HTTPS endpoints. But for development purposes, it should be possible to override this, e.g. with a curl-like `-k | --insecure` flag to `feditest run`.

**Comment by jernst** [comment]
That should be a parameter for the `Imp`.

**Comment by steve-bate** [comment]
I think that only a specific test for valid certificates should fail when the certificate can't be verified and that specific test should detect the condition (using the verify=True override for the request). Otherwise, we'll see related "shadowing" of test results by unrelated failures. We either need to consider Imp a test fixture or create one to use instead of Imp to avoid these kinds of shadowing effects. See also: #235

**Comment by jernst** [comment]
What about:

1) we create one WebFinger test that tests for valid certs
2) all other WebFinger tests still require https but don't fail if the cert is invalid
3) there's a flag of some kind that causes all tests to run against http not https so the tests can be run in "development mode" without cert at all (and skips the test from 1))

Although while this works for WebFinger, I'm not certain how this translates into ActivityPub tests.

**Comment by steve-bate** [comment]
I like 1 and 2. The current verify argument to the Imp get operation will support those.

I don't understand 3 since WebFinger requires https for serving the resource data. Some servers might redirect http to https, but others might just refuse the request.

**Comment by jernst** [comment]
A personal example for 3): My production setup is Apache as a reverse proxy in front of my application that listens at a locally-provisioned port. Apache is the TLS endpoint, the application knows nothing of TLS. (My setup is Java, but it would be the same if the application were in a Docker container or a separate Go process or such.) During development, I may not run that reverse proxy but talk to my application directly at a local port over HTTP. It would be nice if I could run FediTest tests in that setup while developing.

**Comment by steve-bate** [comment]
> I may not run that reverse proxy but talk to my application directly at a local port over HTTP. It would be nice if I could run FediTest tests in that setup while developing.

Couldn't you run your test with an http endpoint for the node and then disable/skip the https requirement test (including cert validity)? AFAIK, that's the only one that would need verify=True when the resource is being request.  

The other tests shouldn't be affected by http vs https or by TLS cert validity.

**Comment by jernst** [comment]
I like the plan of letting N-1 tests pass regardless of whether it is `http`, `https` with valid cert, or `https` with invalid cert. The Nth test then would check that it is `https` with a valid cert.

That leads to https://github.com/fediverse-devnet/feditest-tests-fediverse/issues/126

Secondly, I think we need a flag that instructs the Imp, and where we bypass the Imp and the test acts as an http client itself, to speak `http` instead of `https` when putting webfinger URLs together. That leads to #253.

If that sounds about right, let's close this issue.

**Comment by steve-bate** [comment]
> If that sounds about right, let's close this issue.

I'd like to think about this a bit more.

The Imp `perform_webfinger_query` uses the hostname from the resource (which may not have a hostname, depending on the URL scheme) to create an endpoint URL using `construct_webfinger_uri_for`. The `construct_webfinger_uri_for` hard-codes an "https" scheme for the request. This is reasonable since it's a WebFinger requirement, but if you want flexibility for local nonstandard HTTP testing, then it must be configurable. 

You're suggesting doing this on the client side, but adding a "nonsecure" parameter for the server is another option (to be used by `construct_webfinger_uri_for` to select the scheme). Yet another option is to specify the full WebFinger URL endpoint (or at least a scheme://hostname prefix) in the server config rather than just a hostname. 

Only supporting http seems like more of a server-side consideration, so I like the server-side node parameterization better. I'm not sure yet how this information is passed to the WebFinger client. We could optionally pass a `WebFingerServer` to the `perform_webfinger_query` ( e.g., `perform_webfinger_query(uri_or_server: str|WebFingerServer, rels: list[str] | None)`?). We'd need to experiment a bit.

However, I think we're conflating two separate topics here. One is whether to use https or http for nonstandard local testing. The other is whether TLS certs are verified when using https (either remote or local). My comments above are about the first topic. For the second topic we can add a `verify` kwarg to `WebClient.http` and pass it down from `perform_webfinger_query`. Of course, most real WebFinger clients are going to *always* verify TLS certs. If we start using real (non-Imp) WebFinger clients to test servers, then we would need to revisit this approach.

Side note: the current implementation ignores the `hostname` config in the node and always queries an endpoint based on the resource URL's hostname  (or fails for resource URIs that don't have or require a hostname). 

Another side note: WebFinger resources can be queried from *any* WebFinger endpoint, not just the one with the same hostname as the resource URI. The current implementation doesn't support this scenario, which is fine since the current tests don't require it. However, I think a general purpose WebFinger client should support specifying the WebFinger URL endpoint/prefix and the resource URI separately.
