### ISSUE TITLE
Subprocess Driver?

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#61]
Do you think it would be useful to have a subprocess driver that would support provisioning and unprovision a node using a shell script (or some other program)? This would be a more automated approach than the manual driver but not as full-featured as the UBOS driver. It might also be useful for integration testing of the framework outside of a UBOS container.

**Comment by jernst** [comment]
What would be a specific usage scenario?

**Comment by jernst** [comment]
This certainly can be done. I'm struggling to understand, though, which application I would want to deploy that way in preference to others. Because something production-ready isn't really viable that way (Database provisioning ... needs real web server ... fan-out daemons etc.). And then there is still the port 80/443 problem, the requires-https problem etc.

Suggest if/when we come across something that looks like we'd like to deploy that way, we package it into a script, and, first, manually run that script with the manual driver https://github.com/fediverse-devnet/feditest/blob/develop/src/feditest/nodedrivers/manual/__init__.py that runs outside of UBOS just fine. That would just be a single manual command. If that turns out to be a good setup, we can just copy the manual driver and add a subprocess.run.
